### ISSUE TITLE
GetAllUserKeys or GetAllUserInfo. I need a hybrid.

### ISSUE THREAD

**Issue by getsetbro** [drohreo/spPeoplePicker-ng-directive#2]
For me in my current app I could really use a hybrid of GetAllUserInfo that just gets and stores Key and DisplayText. Can you show me where I might add that?

```
if (!scope.getAllInfo) {
  //var keys = peoplePicker.GetAllUserKeys().split(';');
  ngModelCtrl.$setViewValue(peoplePicker.GetAllUserKeys());
} else {
  ngModelCtrl.$setViewValue(peoplePicker.GetAllUserInfo());
}
```

I tried changing the above to

```
if (!scope.getAllInfo) {
  //var keys = peoplePicker.GetAllUserKeys().split(';');
  ngModelCtrl.$setViewValue(peoplePicker.GetAllUserKeys());
} else {
  var obj = peoplePicker.GetAllUserInfo();
  ngModelCtrl.$setViewValue( {Key: obj[0].Key, DisplayText: obj[0].DisplayText} );
}
```

but no go.

**Comment by ohritz** [comment]
I tested making your change, and I could get a model out no problem, but propogating the picker from code, by way of the model didnt work, which turned out to be a bug in the $render function.

either way, I think you would want to change the render function and the formatterss function if you just wanted a simplified model of the user.

**Comment by getsetbro** [comment]
Can you show me an example?
